/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cashier;
import admin.SalesInputPanel;
import admin.pnlWelcome;
import admin.pnlFeedback;
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author WorldBank13
 */
public class Cashier_Interface extends javax.swing.JFrame {

    /**
     * Creates new form Cashier_Interface
     */
    public Cashier_Interface() {
        initComponents();
        
        //Create a cardlayout and set the content
        CardLayout objLayout = new CardLayout();
        pnlContent.setLayout(objLayout);
        
        //Create a new object pnlWelcome and add to the layout
        pnlWelcome objWelcome = new pnlWelcome();
        pnlContent.add(objWelcome, "0");
        objLayout.show(pnlContent,"0");
        
        //create a new object SalesInputPanel and add to the layout
        SalesInputPanel objSales = new SalesInputPanel();
        pnlContent.add(objSales, "1");
        
        //Create a new object pnlFeedback and add to the layout
        pnlFeedback objFeedback = new pnlFeedback();
        pnlContent.add(objFeedback, "2");
        
          //showing the panel Welcome
        btnHome.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				objLayout.show(pnlContent,"0");
			}
	});
        
         //showing the panel Welcome
        btnCashier.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				objLayout.show(pnlContent,"1");
			}
	});
        
         //showing the panel Feedback
        btnFeedback.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				objLayout.show(pnlContent,"2");
			}
	});
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlButtons = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnCashier = new javax.swing.JButton();
        btnFeedback = new javax.swing.JButton();
        pnlContent = new javax.swing.JPanel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cashier_Interface");
        setPreferredSize(new java.awt.Dimension(940, 680));
        getContentPane().setLayout(null);

        pnlButtons.setMinimumSize(new java.awt.Dimension(151, 286));
        pnlButtons.setOpaque(false);
        pnlButtons.setLayout(new java.awt.GridLayout(3, 1, 15, 10));

        btnHome.setBackground(new java.awt.Color(1, 50, 67));
        btnHome.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("Home");
        pnlButtons.add(btnHome);

        btnCashier.setBackground(new java.awt.Color(1, 50, 67));
        btnCashier.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        btnCashier.setForeground(new java.awt.Color(255, 255, 255));
        btnCashier.setText("Sales Input");
        pnlButtons.add(btnCashier);

        btnFeedback.setBackground(new java.awt.Color(1, 50, 67));
        btnFeedback.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        btnFeedback.setForeground(new java.awt.Color(255, 255, 255));
        btnFeedback.setText("Feedback");
        pnlButtons.add(btnFeedback);

        getContentPane().add(pnlButtons);
        pnlButtons.setBounds(10, 190, 190, 270);

        pnlContent.setOpaque(false);
        pnlContent.setPreferredSize(new java.awt.Dimension(700, 610));

        javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
        pnlContent.setLayout(pnlContentLayout);
        pnlContentLayout.setHorizontalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        pnlContentLayout.setVerticalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        getContentPane().add(pnlContent);
        pnlContent.setBounds(210, 20, 700, 610);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cashier/Pup-Campus.jpg"))); // NOI18N
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 940, 680);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cashier_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cashier_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cashier_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cashier_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cashier_Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCashier;
    private javax.swing.JButton btnFeedback;
    private javax.swing.JButton btnHome;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlContent;
    // End of variables declaration//GEN-END:variables
}
