/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nania Bznz
 */
public class dlgInventory extends javax.swing.JDialog {
    
    protected pnlInventory pnlinventory;

    /**
     * Creates new form dlgInventory
     */
    public dlgInventory(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void refreshtble() {
		DefaultTableModel model = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int rowIndex, int columnIndex) {
                  return false;
                }
                };
		model.addColumn("Product");
		model.addColumn("Quantity");
                
		try {
			Class.forName("com.mysql.cj.jdbc.Driver");
			Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pos_db", "root",
					"meetup73");

			String query = "Select ProductName, Quantity from tblinventory";
			java.sql.Statement stmt = con.createStatement();
			ResultSet rs = stmt.executeQuery(query);

			while (rs.next()) {
				model.addRow(new Object[] { rs.getString("ProductName"), 
                                    rs.getString("Quantity") });
			}

			rs.close();
			stmt.close();
			con.close();

			pnlinventory.tblProducts.setModel(model);
		} catch (Exception e) {
			
			e.printStackTrace();
		}
	}
    
    public void editInv(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pos_db", "root",
					"meetup73");
                        
            java.sql.Statement stmt = con.createStatement();
			
            stmt.execute("UPDATE tblinventory "
                + "SET ProductName = '" + txtProductdlg.getText() + "', Quantity = '"
                                        + txtQuantitydlg.getText() + "', Price = '" + txtPricedlg.getText() + "' "
                + "WHERE ProductName = '" + txtProductdlg.getText() + "'");
                        
            stmt.close();
            con.close();
            
            refreshtble();
            
        } catch (Exception e) {
			
            e.printStackTrace();
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPricedlg = new javax.swing.JLabel();
        txtPricedlg = new javax.swing.JTextField();
        lblProductNamedlg = new javax.swing.JLabel();
        txtProductdlg = new javax.swing.JTextField();
        lblQuantitydlg = new javax.swing.JLabel();
        txtQuantitydlg = new javax.swing.JTextField();
        btnDonedlg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lblPricedlg.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        lblPricedlg.setText("Price");

        txtPricedlg.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        txtPricedlg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPricedlgActionPerformed(evt);
            }
        });

        lblProductNamedlg.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        lblProductNamedlg.setText("Product Name:");

        txtProductdlg.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        lblQuantitydlg.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        lblQuantitydlg.setText("Quantity:");

        txtQuantitydlg.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        btnDonedlg.setText("Done");
        btnDonedlg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonedlgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(btnDonedlg, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(51, 51, 51)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtProductdlg, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblProductNamedlg)
                        .addComponent(lblQuantitydlg)
                        .addComponent(txtPricedlg, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPricedlg)
                        .addComponent(txtQuantitydlg, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(51, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(304, Short.MAX_VALUE)
                .addComponent(btnDonedlg, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(19, 19, 19)
                    .addComponent(lblPricedlg)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtPricedlg, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lblProductNamedlg)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtProductdlg, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lblQuantitydlg)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtQuantitydlg, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(98, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPricedlgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPricedlgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPricedlgActionPerformed

    private void btnDonedlgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonedlgActionPerformed
        editInv();
        dispose();
        pnlinventory.btnEdit.setEnabled(false);
    }//GEN-LAST:event_btnDonedlgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgInventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dlgInventory dialog = new dlgInventory(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDonedlg;
    private javax.swing.JLabel lblPricedlg;
    private javax.swing.JLabel lblProductNamedlg;
    private javax.swing.JLabel lblQuantitydlg;
    public static javax.swing.JTextField txtPricedlg;
    public static javax.swing.JTextField txtProductdlg;
    public static javax.swing.JTextField txtQuantitydlg;
    // End of variables declaration//GEN-END:variables
}
